### PR TITLE
fix(log): adding new-logo

### PR DESCRIPTION
**Pull request by rubychilds**

### CODE REVIEW

**Comment by brannondorsey** [comment]
Where is the `assets/banner.png` file? I'm not seeing it here 🤔

**Comment by rubychilds** [comment]
@brannondorsey It is there https://github.com/runwayml/model-sdk/blob/81e61f1ee4e2f16e4f54ce1a7877f56e759cb751/assets/banner.png

Also you can view the SDK repo for this branch too https://github.com/runwayml/model-sdk/tree/81e61f1ee4e2f16e4f54ce1a7877f56e759cb751

**Comment by brannondorsey** [comment]
Ah, of course! I was looking at master, sorry. I didn't realize GitHub search didn't search branches.

**Comment by rubychilds** [comment]
No prob. It seems github has an issue, when you view branch occasionally it looks like image isn't showing on readme, but see image I attached

**Comment by brannondorsey** [comment]
I wonder if that's because the banner image is so big and its failing to load. Does the network tab in the dev console suggest as much? 2+ MB is pretty massive for a README image that will only be rendered in the web. Maybe we should downscale it.

**Pull request merged**
